### ISSUE TITLE
Additional metric support?

### ISSUE THREAD

**Issue by kashalls** [kubebadges/kubebadges#11]
Would it be possible to include support for different badges as well like:

- How many {{ insert resource type }} out of all are healthy (how many have the ready condition).
- Different to global (cpu/ram) usage compared to global total (cpu/ram) usage
- Average node uptime parsed into week/day/month/hours/seconds

**Comment by szpnygo** [comment]
There's a preliminary plan to expand the range of badges, but no specific timetable has been set for its completion.

**Comment by szpnygo** [comment]
On the website, I've left a menu for generating additional badges. My vision is that this can be used to create things like labels/annotations for resources, or even custom requests.
